apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-webapp-cve-processor.fullname" . }}
  labels:
    {{- include "helm-webapp-cve-processor.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "helm-webapp-cve-processor.selectorLabels" . | nindent 4 }}
  ports:
    - name: application
      protocol: TCP
      port: {{ .Values.serverPort }}
      targetPort: {{ .Values.serverPort }}
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30000